language: objective-c
matrix:
  include:
    - language: cpp
      os: osx
      osx_image: xcode11.3

before_install:
  - brew tap david0/homebrew-audio 
  - brew update

script:
  # zita will be implicitly installed, ardour takes too long
  - brew install --formula `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour|zita'`
  - brew test `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour|zita'`

notifications:
  email:
    on_success: never
    on_failure: always
