language: objective-c
matrix:
  include:
    - language: cpp
      os: osx
      osx_image: xcode11.3

before_install:
  - brew tap david0/homebrew-audio 
  - brew update

script:
  - travis_wait brew install --formula `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour'`
  - brew test `grep -l url Formula/*.rb|grep -vE 'joeboy|ardour'`

notifications:
  email:
    on_success: never
    on_failure: always
